# serene v3.0.0
#
# - docs: https://github.com/isunjn/serene/blob/latest/USAGE.md
# - check for updates: https://github.com/isunjn/serene/releases
#
#=========================================================================================

base_url = "https://pablogguz.github.io/"      # Domain name of your website
title = "pablo garcía-guzmán"
description = "my personal website"
default_language = "en"
theme = "serene"
output_dir = "public"
compile_sass = true
minify_html = true
build_search_index = false            # Keep this false, search is temporarily unsupported
generate_feed = false                 # Whether to generate a feed file in root, read docs for more info about rss feed
feed_filename = "feed.xml"            # The file name of feed, "feed.xml" / "atom.xml" / "rss.xml", read docs for more info
taxonomies = [{ name = "tags" }, { name = "categories" }]

[markdown]
highlight_code = true
highlight_theme = "css"
extra_syntaxes_and_themes = ["syntaxes", "highlight_themes"]
highlight_themes_css = [
    { theme = "serene-light", filename = "hl-light.css"},
    { theme = "serene-dark", filename = "hl-dark.css"},
]
render_emoji = false
external_links_target_blank = false
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

#=========================================================================================

[extra]

name = ""                         # Your name
id = "pablo garcía-guzmán"                           # Your id / username / handle
bio = ""                          # Your bio
avatar = "img/profile3.JPG"            # Your avatar
links = [                             # Your links
    { name = "LinkedIn", icon = "linkedin", url = "https://www.linkedin.com/in/pablogguz/" },
    { name = "GitHub", icon = "github", url = "https://github.com/pablogguz" },
    { name = "Twitter", icon = "twitter", url = "https://twitter.com/pablogguz_" },
    { name = "Email", icon = "email", url = "mailto:<pgarcia.eco@gmail.com>" },
]

homepage_layout = "about"             # "about" | "list" | "recent"

recent_max = 15
recent_more = true
recent_more_text = "more »"

sections = [
    { name = "blog", path = "/blog", is_external = false },
    { name = "data projects", path = "/projects", is_external = false },
    { name = "policy", path = "/policy", is_external = false }
    # { name = "about", path = "/about", is_external = false },
    # { name = "github", path = "https://github.com/<your-username>", is_external = true },
]
blog_section_path = "/blog"

nav_separator = "::"
nav_wrapper_left = "{"
nav_wrapper_right = "} ;"
nav_wrapper_separator = ","

display_id = false                     # Whether to display your id on homepage
blog_categorized = false               # Whether to categorize blog posts
blur_effect = true                    # Whether to turn on blur effect on navigation bar
back_to_top = true                    # Whether to show back-to-top button on post pages

toc = true                            # Whether to show Table-Of-Contents by default
copy = true                           # Whether to add a copy button on code blocks by default
comment = false                       # Whether to show giscus comment section by default, see https://giscus.app for more info
display_tags = true                   # Whether to display tags on post pages by default
truncate_summary = false              # Whether to truncate the summary of a post by default

outdate_alert = false                 # Whether to show outdate alert by default
outdate_alert_days = 120              # How many days will a post be outdated by default
outdate_alert_text_before = "This article was last updated "
outdate_alert_text_after = " days ago and may be out of date."

footer_copyright = "made by pablo w/ ❤️ © 2024"
footer_disclaimer = "All the content shared on this website is completely my own and does not reflect the views of the EBRD"

footer_credits = true                 # Whether to show "powered by zola and serene" in footer

not_found_title = "404"
not_found_error_text = "Not Found"
not_found_recover_text = "« back to home »"

reading_time = 0                    # Reading time 

# Coffee modal config
coffee_modal = true
coffee_text = "fancy a (virtual) coffee?"
coffee_guidelines = [
    """
    Don't be shy! I'm always happy to chat about data, economics, or anything else. 
    If you are a student or just starting out in the field, I'm also happy to provide advice 
    or guidance on the usual stuff (e.g. whether to do a PhD, whether a pre-doc is worth it, 
    alternative career paths, etc.).
    """,
    """
    If you add me on LinkedIn, please drop a brief note explaining why you want to connect. 
    I generally don't accept invites without context (unless we're clearly in the same data/econ research bubble).
    """,
    """
    I am not a hiring manager and can't provide specific interview advice for EBRD roles.
    If you ask me about this, I will refer you to publicly available resources and wish you the best of luck!
    """
]